### ISSUE TITLE
Stats | Tab switching takes a long time

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-commons#55] opened 2017-02-22 17:55 UTC
# Description:
On Caseflow and eFolder Express,
When switching Tabs between _Hourly_,_Daily_, etc.
It takes a while for each tab to load,
maybe would be useful to have a loading animation (otherwise it feels like the click did not go through)

**Type of Bug:**
- [ ] Functional

- [X] UI

- [ ] Security

- [ ] Tech Improvement

**Severity Level:**

**`dev`,`uat`**

# Reproductive Steps
**Scenario 1:**
**`dev`**

1. Access `/stats` page

2. Click on any tab not currently in view

3. Observe how long it takes to load

4. Wonder if your click actually worked..

5. Click again

6. Observe that the new tab showed up finally

# Screen Shots
**_Scenario 1 - `dev` eFolder `/stats`_**

![brokenstats](https://cloud.githubusercontent.com/assets/18075411/23224656/3b82c688-f8fd-11e6-8c5e-aeda636bd7b3.gif)

**_Scenario 2 - `uat` Caseflow Certification_**
![longstatsuat](https://cloud.githubusercontent.com/assets/18075411/23224909/12025ca0-f8fe-11e6-93bd-b18f141c8931.gif)

# Relate Stories/Issues
**_Support Tickets/Features/Issues_**

**Comment by kierachell** [comment] 2017-02-23 00:00
Need designer input on how to handle this _gracefully_

**Comment by lakohl** [comment] 2017-03-23 12:50
assigning this to @gnakm for guidance. Loading indicator may be merited

**Comment by gnakm** [comment] 2017-03-29 17:37
Hey @kierachell -- just to make sure I am understand what's on at the top because it's a little hard to tell with the screen recording. The problem is that it is taking time to load into the next tab, correct? Not necessarily the graphs on the page aren't loading fast enough.

**Comment by kierachell** [comment] 2017-04-01 02:05
There might be two issues here:

1. Should the graphs just load faster? That's a developer issue (that's why the bug is not a `bug-ui`)
1. If not 1. then should we have a loading indicator or some response that _action is taking place hang on a moment_

**Comment by gnakm** [comment] 2017-06-27 15:10
@kierachell Is this still persisting?

**Comment by kierachell** [comment] 2017-06-27 16:16
It's not too bad, close this if the following is acceptable:
![nottoobad](https://user-images.githubusercontent.com/18075411/27598080-60228a2c-5b32-11e7-94ea-a04c65929672.gif)

**Comment by lakohl** [comment] 2017-06-27 16:33
Are you testing in prod? Just wondering if the lag time is the same in the test environment...

**Comment by gnakm** [comment] 2017-06-27 16:40
This new gif is helpful because it's showing that it's not the individual graphs but the tabs and the Dashboard name on the top nav. I think it would be an over kill to have loaders in every tab. What about have "_Loading..._" where Dashboard should be at the top nav in the same style as Saving... in Hearing worksheet?

**Comment by lakohl** [comment] 2017-06-27 16:48
@gnakm Agree about the overkill and I like the 'Loading...' idea

**Comment by kierachell** [comment] 2017-06-29 01:08
Can't test on prod...because...CSS...ISO... :(

**Comment by gnakm** [comment] 2017-12-13 20:27
This is a v. minor bug. I'm going to close this. If we need to revisit it, it has the won't fix label and we can find later.

**Closed by gnakm** 2017-12-13 20:27 UTC
Labels: Backlog, bug-low-priority
