### ISSUE TITLE
Update Google Fonts in Caseflow Commons

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#9] opened 2016-10-31 22:53 UTC
The version of Source Sans we use in Caseflow Commons is out of date w/ Google Fonts & USDWDS. We should update the font files to the latest from USWDS. Specifically we want the following wieghts from Google:

- Bold
- Regular 
- Regular Italic

**Comment by KHarshawat** [comment] 2016-12-19 16:44
For example, eFolder express uses the following H1

![image](https://cloud.githubusercontent.com/assets/6335546/21320839/551c2df0-c5e0-11e6-84e1-a68b192a8e16.png)

But the web standards h1 looks like the following

![image](https://cloud.githubusercontent.com/assets/6335546/21320846/61ac3c7c-c5e0-11e6-9940-245efb288b7b.png)

Both are listed at `font-weight: 700` in the dom so something is fishy here.

**Comment by KHarshawat** [comment] 2016-12-19 18:44
@mmlumba should be working on this now.

**Comment by mmlumba** [comment] 2016-12-21 21:59
@KHarshawat For your h1 example, the bold style change will impact anything that has a header (`h1-h6`). Would this be ok? See below; the eFolder Express logo is an `h1`, and as such it will also be bold:
<img width="1078" alt="screen shot 2016-12-21 at 1 55 20 pm" src="https://cloud.githubusercontent.com/assets/4773320/21407689/b67ab2f0-c785-11e6-9aac-35a1c6581c5a.png">

**Comment by mmlumba** [comment] 2017-01-04 02:23
@KHarshawat check out PR #26 for the rest of the screenshots

**Comment by mmlumba** [comment] 2017-01-04 15:59
@astewarttistatech @kierachell Instructions for testing listed in above PR ("Changing font files")

**Comment by kierachell** [comment] 2017-01-05 14:13
Here are before -> after mugshots on __Feedback__;

Looks good in `dev` as far as I can tell.


@astewarttistatech got screenshots from other apps.


<img width="277" alt="screen shot 2017-01-05 at 09 01 51" src="https://cloud.githubusercontent.com/assets/18075411/21683152/2211fdb0-d326-11e6-9c29-9e7ba3e32ef3.png">
<img width="254" alt="screen shot 2017-01-05 at 09 00 54" src="https://cloud.githubusercontent.com/assets/18075411/21683153/22137db6-d326-11e6-80d7-594ba162ec10.png">


<img width="960" alt="screen shot 2017-01-05 at 08 58 49" src="https://cloud.githubusercontent.com/assets/18075411/21683180/3f5e6354-d326-11e6-9485-5fb4de52dfdd.png">
<img width="1010" alt="screen shot 2017-01-05 at 09 00 50" src="https://cloud.githubusercontent.com/assets/18075411/21683181/3f62329a-d326-11e6-82ba-c08cd9e3ea0f.png">

<img width="977" alt="screen shot 2017-01-05 at 08 59 08" src="https://cloud.githubusercontent.com/assets/18075411/21683304/c2e5666e-d326-11e6-99d9-269e2e422fa2.png">
<img width="1010" alt="screen shot 2017-01-05 at 09 00 50" src="https://cloud.githubusercontent.com/assets/18075411/21683305/c2e5d892-d326-11e6-8d0e-4303ddd59869.png">


<img width="1053" alt="screen shot 2017-01-05 at 08 59 18" src="https://cloud.githubusercontent.com/assets/18075411/21683372/15b1335a-d327-11e6-963a-789a950a8d45.png">
<img width="1083" alt="screen shot 2017-01-05 at 09 01 07" src="https://cloud.githubusercontent.com/assets/18075411/21683373/15d5b842-d327-11e6-8cf5-feac9bbecf0a.png">

**Comment by kierachell** [comment] 2017-01-06 14:17
Question @KHarshawat & @mmlumba 

In Manage Claim Establishment the following font was changed as well:
<img width="340" alt="screen shot 2017-01-06 at 09 15 05" src="https://cloud.githubusercontent.com/assets/18075411/21720377/ba4c0376-d3f0-11e6-95da-94cc10f61b62.png">

But not a _similar_ text for Caseworker:
<img width="262" alt="screen shot 2017-01-06 at 09 16 27" src="https://cloud.githubusercontent.com/assets/18075411/21720401/da57588c-d3f0-11e6-8b44-db25a3e0a839.png">

Is this intended behavior?

**Comment by astewarttistatech** [comment] 2017-01-06 15:35
@kierachell It was determined that that is not expected behavior per my conversation with Kavi. This  is a separate issue from the font changed.

**Comment by astewarttistatech** [comment] 2017-01-06 15:40
Please see attached for images of the change in Efolder Express.
![efolder express - help page](https://cloud.githubusercontent.com/assets/23038505/21722898/7fb2b06e-d3fc-11e6-80c8-6ce45dfac9a9.png)
![efolder express - hp](https://cloud.githubusercontent.com/assets/23038505/21722900/7fcaef6c-d3fc-11e6-9f0e-2be2a3d48cfa.png)
![efolder express - loading user](https://cloud.githubusercontent.com/assets/23038505/21722899/7fc89f96-d3fc-11e6-923a-d6c2aaaf38f9.png)
![efolder express - success](https://cloud.githubusercontent.com/assets/23038505/21722901/7fdd2d94-d3fc-11e6-9ce6-1c094ae5a1e9.png)

**Comment by astewarttistatech** [comment] 2017-01-06 15:58
Please see attached for the screenshots of Caseflow Dispatch and Certification.

![caseflow certification - caseworker establish claim](https://cloud.githubusercontent.com/assets/23038505/21723550/e65263d0-d3fe-11e6-8c5d-647f9eaf1e5e.png)
![caseflow certification - certify appeal](https://cloud.githubusercontent.com/assets/23038505/21723552/e6589534-d3fe-11e6-89cf-8ed6386a1bb5.png)
![caseflow certification - congrats appeal](https://cloud.githubusercontent.com/assets/23038505/21723551/e658a696-d3fe-11e6-8de6-bb4855660bb4.png)
![caseflow certification - congrats page](https://cloud.githubusercontent.com/assets/23038505/21723555/e65c3ed2-d3fe-11e6-87fb-0f2ef37d5c20.png)
![caseflow certification - create end product](https://cloud.githubusercontent.com/assets/23038505/21723554/e65c4b0c-d3fe-11e6-8f26-af49ec8c3dff.png)
![caseflow certification - help](https://cloud.githubusercontent.com/assets/23038505/21723553/e65aa9be-d3fe-11e6-8bfc-d679adcba045.png)
![caseflow certification - manager view](https://cloud.githubusercontent.com/assets/23038505/21723558/e667e002-d3fe-11e6-9b9f-44b683dd0067.png)
![caseflow certification - preview](https://cloud.githubusercontent.com/assets/23038505/21723556/e665cccc-d3fe-11e6-8da4-c541b1474e5f.png)
![caseflow certification - review decision](https://cloud.githubusercontent.com/assets/23038505/21723559/e667fe3e-d3fe-11e6-8a06-b15da9be83dd.png)
![caseflow certification - user page](https://cloud.githubusercontent.com/assets/23038505/21723557/e6674bec-d3fe-11e6-9b18-433117d39310.png)


Moving this issue to Done

**Closed** 2017-01-06 16:00 UTC
